# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm1_gripper_controller
    - arm2_gripper_controller
    - arm1_controller
    - arm2_controller

  arm1_gripper_controller:
    type: GripperCommand
    joints:
      - piper1_joint7
    action_ns: gripper_cmd
    default: true
  arm2_gripper_controller:
    type: GripperCommand
    joints:
      - piper2_joint7
    action_ns: gripper_cmd
    default: true
  arm1_controller:
    type: FollowJointTrajectory
    joints:
      - piper1_joint1
      - piper1_joint2
      - piper1_joint3
      - piper1_joint4
      - piper1_joint5
      - piper1_joint6
    action_ns: follow_joint_trajectory
    default: true
  arm2_controller:
    type: FollowJointTrajectory
    joints:
      - piper2_joint1
      - piper2_joint2
      - piper2_joint3
      - piper2_joint4
      - piper2_joint5
      - piper2_joint6
    action_ns: follow_joint_trajectory
    default: true